### ISSUE TITLE
Where do I download meshes?

### ISSUE THREAD

**Issue by brianpeiris** [seung-lab/gallery#83]
I'm trying to run the gallery locally. The README mentions "Acquire meshes from someone who has them". Are the meshes available to download somewhere (other than scraping them from museum.eyewire.org)?

**Comment by william-silversmith** [comment]
Here you go! https://drive.google.com/file/d/1-qmE1sEL3AIGpNfi0w50MEOgm2WIF4_1/view?usp=sharing

**Comment by william-silversmith** [comment]
I updated the instructions on the main README.md
